[project]
name = "msisim"
version = "0.0.1"

authors = [{ name = "Martin Metodiev", email = "m.d.metodiev7@gmail.com" }, 
{ name = "Yuting Lu", email = "yuting.lu@tum.de"},
{ name = "Yuchen Xiang", email = "yuchen.xiang11@imperial.ac.uk"}
]

description = "MSI simulation"
readme = "README.md"
dependencies = [
    "numpy",
    "scipy",
    "shapely",
    "matplotlib",
    "seaborn"
]